name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Tailwind CSS
      run: npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css
    
    - name: Run tests
      run: npm test -- --ci --coverage --maxWorkers=2 
